Document: cri-o
Title: Debian cri-o Manual
Author: <insert document author here>
Abstract: This manual describes what cri-o is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/cri-o/cri-o.sgml.gz

Format: postscript
Files: /usr/share/doc/cri-o/cri-o.ps.gz

Format: text
Files: /usr/share/doc/cri-o/cri-o.text.gz

Format: HTML
Index: /usr/share/doc/cri-o/html/index.html
Files: /usr/share/doc/cri-o/html/*.html
